# Generated by Django 6.0.5 on 2026-05-12 15:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100)),
                ('pochta', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('mesto', models.CharField(choices=[('stydent', 'Студент'), ('prepod', 'Преподаватель'), ('glava', 'Начальник'), ('avtor', 'Автор')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Proverks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imya', models.CharField(max_length=200)),
                ('info', models.TextField()),
                ('kogda', models.DateField()),
                ('ststus', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stranica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skidka', models.SlugField(unique=True)),
                ('zagolovok', models.CharField(max_length=200)),
                ('kontent', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Programma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvamie', models.CharField(max_length=200)),
                ('opisanie', models.TextField()),
                ('menedjer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progi_man', to='core.chel')),
                ('rukovoditel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progi_dir', to='core.chel')),
            ],
        ),
        migrations.CreateModel(
            name='Otziv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=100)),
                ('tekst', models.TextField()),
                ('ocenks', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('data_sozdaniya', models.DateTimeField(auto_now_add=True)),
                ('kyrs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otzivi', to='core.programma')),
            ],
        ),
    ]
